language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6-dev"

install:
    - pip install -r requirements.txt
    - pip install codecov

after_success:
    - codecov

script:
    nosetests --with-coverage --cover-package=js2xml tests
