sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6-dev"

install:
    - pip install tox-travis
    - pip install -r requirements.txt
    - pip install codecov

after_success:
    - codecov

script:
    tox
